import type { PlanDraft } from "./schemas";

export const showcasePlan: PlanDraft = {
  id: "showcase-suzhou",
  city: "Suzhou",
  days: 2,
  budget_min: 1200,
  budget_max: 2000,
  transport_preferences: ["drive", "metro"],
  entry_mode: "xiaohongshu",
  travel_mode: "photo",
  preference_tags: ["food", "photo_ready", "night_view"],
  parking_required: true,
  parking_sort: "distance",
  max_walk_from_parking_minutes: 30,
  stay_preference: "boutique_hotel",
  interest_tags: ["museum", "photo_spots", "citywalk"],
  special_requirements: "student discount preferred",
  xiaohongshu_link: "https://www.xiaohongshu.com/example",
  xiaohongshu_notes:
    "苏州博物馆虽然免费但是要提前很久预约，公众号预约。平江路更适合下午慢逛，夜景留到山塘街。",
  output_language: "zh-CN",
  status: "draft",
  summary: "以预约景点优先、出片节奏明确的 2 天苏州执行方案。",
  timeline: [
    {
      day_index: 1,
      start_time: "09:00",
      end_time: "11:30",
      title: "苏州博物馆",
      transport_mode: "metro",
      transport_duration_minutes: 20,
      notes: "上午先把需要预约的馆类点位走完，留出后半天给拍照和慢逛。",
      reservation_hint: {
        poi_name: "苏州博物馆",
        reminder_text: "需要提前预约，公众号可完成实名预约。",
        reservation_channel: "公众号",
        price_note: "免费",
        source_url: "https://www.xiaohongshu.com/example",
        source_type: "xiaohongshu",
        confidence: 0.9,
        evidence_excerpt: "虽然免费但是要提前预约，公众号预约。",
      },
    },
    {
      day_index: 1,
      start_time: "13:00",
      end_time: "15:30",
      title: "平江路",
      transport_mode: "walk",
      transport_duration_minutes: 15,
      notes: "把午后时段留给街巷慢逛和拍照。",
      reservation_hint: null,
    },
    {
      day_index: 1,
      start_time: "18:30",
      end_time: "20:00",
      title: "双塔市集",
      transport_mode: "taxi",
      transport_duration_minutes: 18,
      notes: "适合作为补能和轻量夜拍节点。",
      reservation_hint: null,
    },
    {
      day_index: 2,
      start_time: "19:00",
      end_time: "21:00",
      title: "山塘街",
      transport_mode: "drive",
      transport_duration_minutes: 25,
      notes: "把夜景和收尾放到第二天晚上。",
      reservation_hint: null,
    },
  ],
  map_points: [
    {
      name: "苏州博物馆",
      lat: 31.3246,
      lng: 120.6171,
      day_index: 1,
      sequence_no: 1,
    },
    {
      name: "平江路",
      lat: 31.3197,
      lng: 120.6288,
      day_index: 1,
      sequence_no: 2,
    },
    {
      name: "双塔市集",
      lat: 31.3088,
      lng: 120.6324,
      day_index: 1,
      sequence_no: 3,
    },
    {
      name: "山塘街",
      lat: 31.3324,
      lng: 120.5966,
      day_index: 2,
      sequence_no: 4,
    },
  ],
  budget_items: [
    {
      category: "tickets",
      amount_low: 96,
      amount_high: 240,
      is_adjustable: false,
    },
    {
      category: "food",
      amount_low: 216,
      amount_high: 440,
      is_adjustable: true,
    },
    {
      category: "stay",
      amount_low: 360,
      amount_high: 760,
      is_adjustable: false,
    },
    {
      category: "local_transport",
      amount_low: 96,
      amount_high: 240,
      is_adjustable: true,
    },
  ],
  checklist_items: [
    {
      category: "documents",
      item_name: "身份证",
      reason: "用于交通出行和酒店入住核验。",
    },
    {
      category: "documents",
      item_name: "学生证",
      reason: "景点存在学生票时可直接使用。",
    },
    {
      category: "weather",
      item_name: "雨伞",
      reason: "有降雨风险，换乘和步行段都更方便应对。",
    },
    {
      category: "weather",
      item_name: "防晒霜",
      reason: "白天户外节点更适合短袖，并补充防晒。",
    },
  ],
  weather_summary: {
    city_name: "苏州",
    condition_summary: "小雨 -> 多云",
    temperature_low_c: 19,
    temperature_high_c: 31,
    report_time: "2026-06-24 08:00:00",
    overview: "天气预计小雨 -> 多云，19-31°C。",
    clothing_tip: "建议带一件薄外套，并随身带伞。",
    advisory_tags: ["rain", "sun", "layering"],
  },
  execution_summary: {
    headline: "这趟更适合上午先完成预约景点，下午再转入拍照和慢逛。",
    pace: "balanced",
    transport_strategy: "地铁 + 短距离步行",
    best_for: ["出片打卡", "周末 2 天"],
  },
  reservation_risks: [
    {
      poi_name: "苏州博物馆",
      severity: "high",
      reservation_channel: "公众号",
      price_note: "免费",
      evidence_excerpt: "虽然免费但是要提前预约，公众号预约。",
    },
  ],
  parking_guides: [
    {
      poi_name: "苏州博物馆",
      parking_difficulty: "一般",
      recommended_lot_name: "苏州博物馆北停车场",
      walking_minutes: 6,
      price_note: "约 8 元/小时",
      sort_mode: "distance",
    },
    {
      poi_name: "山塘街",
      parking_difficulty: "节假日偏紧张",
      recommended_lot_name: "山塘街游客中心停车场",
      walking_minutes: 9,
      price_note: "约 8 元/小时",
      sort_mode: "distance",
    },
  ],
  hotel_area_recommendations: [
    {
      area_name: "平江路东侧",
      parking_convenience: "停车场选择多，适合晚回酒店后步行补逛",
      parking_price_note: "商圈停车多为 6-8 元/小时",
      access_note: "去博物馆、平江路和双塔市集都比较顺路",
      suitable_modes: ["drive", "photo", "citywalk"],
      budget_band: "mid",
    },
    {
      area_name: "金鸡湖东岸",
      parking_convenience: "酒店自带停车位概率更高，进出城压力更小",
      parking_price_note: "高端酒店更常见免费或封顶停车",
      access_note: "适合把古城和湖区拆成两段开车完成",
      suitable_modes: ["drive", "nature"],
      budget_band: "upper_mid",
    },
  ],
  graph: {
    nodes: [
      { id: "city", label: "Suzhou", type: "city" },
      { id: "day-1", label: "Day 1", type: "day" },
      { id: "poi-1", label: "苏州博物馆", type: "attraction" },
      { id: "budget-food", label: "food", type: "budget" },
      { id: "reservation-1", label: "苏州博物馆", type: "reservation" },
    ],
    edges: [
      { source: "city", target: "day-1", label: "contains" },
      { source: "day-1", target: "poi-1", label: "visit" },
      { source: "city", target: "budget-food", label: "budget" },
      { source: "city", target: "reservation-1", label: "reserve" },
    ],
  },
  created_at: "2026-06-24T10:00:00.000Z",
  reservation_hints: [
    {
      poi_name: "苏州博物馆",
      reminder_text: "需要提前预约，公众号可完成实名预约。",
      reservation_channel: "公众号",
      price_note: "免费",
      source_url: "https://www.xiaohongshu.com/example",
      source_type: "xiaohongshu",
      confidence: 0.9,
      evidence_excerpt: "虽然免费但是要提前预约，公众号预约。",
    },
  ],
};
